server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  endpoint:
    health:
      show-details: always

spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

  datasource:
    url: jdbc:mysql://192..168.0.17:3306/Eventory
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: EventoryUser
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.boot.actuate.endpoint: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
